### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by story-x** [hewang1an/StarRail-plugin#115]
![image](https://github.com/hewang1an/StarRail-plugin/assets/45375162/8637d0a1-608c-475e-9d3f-bbae48a9fcbb)

根目录执行  pnpm install -P 后还是报错（install无任何报错）

**Comment by Night-stars-1** [comment]
pnpm i

**Comment by story-x** [comment]
> PNPM我

必须装dev环境吗？

**Comment by story-x** [comment]
> pnpm i

可以不装dev环境不？

**Comment by zipated** [comment]
我是把 package.json 的 devDependencies 改成 dependencies

**Comment by bietiaop** [comment]
已经将 devDependencies 依赖移至 dependencies。
