### ISSUE TITLE
Keeping in touch

### ISSUE THREAD

**Issue by Sinkira** [hewang1an/StarRail-plugin#116]
Hello, 

What communication channels do you devs use? 
If I were to use the API i want to keep in touch with the developers.

I know you don't use Discord as of recently, so where do I find you guys?

Thanks.

**Comment by hewang1an** [comment]
Hello,

You can come to our Telegrem. Our main developers are here.
https://t.me/+zpptyFptARkwMDg9

**Comment by TsukinaKasumi** [comment]
Hello,

You can come to our Telegram. Our main developers are here.
https://t.me/+zpptyFptARkwMDg9
