### ISSUE TITLE
查询攻略4,5,6时报错

### ISSUE THREAD

**Issue by Fahaxikiii** [hewang1an/StarRail-plugin#117]
![image](https://github.com/hewang1an/StarRail-plugin/assets/93320886/f43e0e69-b0da-4cfd-9616-fc055dabb19c)
TypeError: Cannot read properties of undefined (reading 'forEach')
0|Miao-Yun |     at strategy.getImg (file:///disk/bot/Miao-Yunzai/plugins/StarRail-plugin/apps/strategy.js:150:31)
0|Miao-Yun |     at strategy (file:///disk/bot/Miao-Yunzai/plugins/StarRail-plugin/apps/strategy.js:104:20)
0|Miao-Yun |     at PluginsLoader.deal (file:///disk/bot/Miao-Yunzai/lib/plugins/loader.js:289:57)
0|Miao-Yun |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by simo8102** [comment]
StarRail-plugin/apps/strategy.js第150行改成这样临时解决

 if(this.collection_id[group]){
    this.collection_id[group].forEach((id) => msyRes.push(this.getData(this.url + id)))
    }

**Comment by Fahaxikiii** [comment]
>    
> StarRail-plugin/apps/strategy.js第150行改成这样临时解决
> 
>  if(this.collection_id[group]){
>     this.collection_id[group].forEach((id) => msyRes.push(this.getData(this.url + id)))
>     }

好的，感谢！我试试去

**Comment by ZM-J** [comment]
> StarRail-plugin/apps/strategy.js第150行改成这样临时解决
> 
> if(this.collection_id[group]){ this.collection_id[group].forEach((id) => msyRes.push(this.getData(this.url + id))) }

这样改的目的是啥 是因为攻略不存在使得 `this.collection_id[group]` 的值为 `undefined` 吗？

**Comment by bietiaop** [comment]
目前 @simo8102 提了一个 pr，请查看是否已经解决问题

**Comment by Fahaxikiii** [comment]
> 目前 @simo8102 提了一个 pr，请查看是否已经解决问题

感谢。没有报错了。
发送*符玄攻略6会回复
暂无符玄攻略（undefined）
请尝试其他的攻略来源查询
*攻略帮助，查看说明
6是hoyo青枫我看他米游社是有提供攻略的。但是米游社那个攻略图和机器人提供的攻略图不一样

**Comment by bietiaop** [comment]
> > 目前 @simo8102 提了一个 pr，请查看是否已经解决问题
> 
> 感谢。没有报错了。 发送*符玄攻略6会回复 暂无符玄攻略（undefined） 请尝试其他的攻略来源查询 *攻略帮助，查看说明 6是hoyo青枫我看他米游社是有提供攻略的。但是米游社那个攻略图和机器人提供的攻略图不一样

你好，尝试删除 `./plugins/StarRail-plugin/temp/strategy` 目录下的缓存文件试试

**Comment by Fahaxikiii** [comment]
> > > 目前 @simo8102 提了一个 pr，请查看是否已经解决问题
> > 
> > 
> > 感谢。没有报错了。 发送*符玄攻略6会回复 暂无符玄攻略（undefined） 请尝试其他的攻略来源查询 *攻略帮助，查看说明 6是hoyo青枫我看他米游社是有提供攻略的。但是米游社那个攻略图和机器人提供的攻略图不一样
> 
> 你好，尝试删除 `./plugins/StarRail-plugin/temp/strategy` 目录下的缓存文件试试

我好像知道了，他攻略456是在仓库里面的，应该是不支持更新。要自己往里面添加。删除缓存文件只会更新123的攻略图

**Comment by bietiaop** [comment]
> > > > 目前 @simo8102 提了一个 pr，请查看是否已经解决问题
> > > 
> > > 
> > > 感谢。没有报错了。 发送*符玄攻略6会回复 暂无符玄攻略（undefined） 请尝试其他的攻略来源查询 *攻略帮助，查看说明 6是hoyo青枫我看他米游社是有提供攻略的。但是米游社那个攻略图和机器人提供的攻略图不一样
> > 
> > 
> > 你好，尝试删除 `./plugins/StarRail-plugin/temp/strategy` 目录下的缓存文件试试
> 
> 我好像知道了，他攻略456是在仓库里面的，应该是不支持更新。要自己往里面添加。删除缓存文件只会更新123的攻略图

这个我不太清楚，更多攻略应该是其他插件集成的，这方面可以去问一下其他插件的大佬。如果没有其他问题将关闭此 issue。
