### ISSUE TITLE
面板 API 问题，请求适配 mihomo api

### ISSUE THREAD

**Issue by amefs** [hewang1an/StarRail-plugin#121]
目前欧服无法使用以下三种面板 api
- https://avocado.wiki/v1/info/
- https://lulu.roki.best/v1/info/
- https://sr.roki.best/v1/info/

已知 [mihomo](https://api.mihomo.me/sr_info/) 查询依然正常，但是格式有区别，请求适配。

**Comment by bietiaop** [comment]
你好，
为了减少插件维护成本，我们直接使用了格式化后的 API 数据①，但是由于 Avocado API 与 Mihomo API 开发者不同，二者对于 raw_data 的格式化结构不同②。对此的直接解决办法就是使用原始数据（raw_data）进行解析，这可能需要重构面板功能。但是由于目前开发者处于**非活跃状态**，许多功能缺乏维护，对于面板的重构这种大工程实施的可能性就更小了。
如果你有意向解决此问题，欢迎进行 pr :)

> 注：
> ①我们使用 StarRailData 等仓库里的游戏数据对 raw_data 进行解析，使 API 数据可读性增加。考虑到这些仓库文件错综复杂，我们将解析工作放到了服务器上，因此当游戏数据进行更新时，我们仅需更新服务器中的仓库即可，若将这些文件放到插件中，维护起来更加麻烦，也会增加插件的更新频率，使用难度提升。
> ②对于 Avocado 于 Mihomo，都有一套自己的解析数据结构，在前期并没有统一规范，导致了二者结构差异很大。详见 [Avocado API 格式](https://avocado.wiki/v1/info/100570412)；[Mihomo API 格式](https://api.mihomo.me/sr_info_parsed/100570412)。但是我们的 API 都提供了原始数据：[Mihomo API](https://api.mihomo.me/sr_info/100570412)；[Avocado API](https://avocado.wiki/v1/raw/info/100570412)。这是未经处理的原始数据，数据结构是一致的。
