### ISSUE TITLE
星穹铁道插件增加角色攻略查看建议

### ISSUE THREAD

**Issue by WaveCai** [hewang1an/StarRail-plugin#13]
大佬能加个角色攻略查看的功能吗，我看原神那边攻略功能的使用率还是挺高的，如果能加上功能感激不尽

**Comment by SmallK111407** [comment]
后续有人做攻略的话会考虑加入，现在请移步[图鉴Atlas](https://github.com/Nwflower/atlas)，其星铁图鉴算半个攻略，角色推荐了光锥和搭配角色以及材料

**Comment by WaveCai** [comment]
好的，谢谢
