### ISSUE TITLE
查询*末日报错：Cannot read properties of null (reading 'icon')] 

### ISSUE THREAD

**Issue by Strawxg** [hewang1an/StarRail-plugin#155]
![image](https://github.com/user-attachments/assets/d8480c4e-4e8e-44d5-95c5-06697dec9885)
图片形式
报错代码
[16:41:20.748][INFO][3237598850 <= 582639970, 3629718646] 群消息：[游戏爱好者交流群, Straw] *末日
[16:41:20.759][INFO][582639970, Straw(3629718646)][*末日][星铁plugin-深渊(challengeBoss)][开始处理]
[16:41:20.954][MARK][TRSSYz] [米游社接口][getFp][] 193ms
[16:41:21.158][MARK][TRSSYz] [米游社接口][srUser][] 202ms
[16:41:21.263][MARK][TRSSYz] [米游社接口][getFp][113849981] 53ms
[16:41:21.515][MARK][TRSSYz] [米游社接口][srChallengeBossSimple][113849981] 251ms
[16:41:21.728][MARK][TRSSYz] [米游社接口][srChallengeBoss][113849981] 211ms
[16:41:21.736][ERRO][582639970, Straw(3629718646)][*末日][星铁plugin-深渊(challengeBoss)] [Error [TemplateError]: anonymous:174:53
    172|                     <div class="buff-col">
    173|                       <div class="buff-icon-container">
 >> 174|                         <img class="buff-icon" src="{{ floor.node_2.buff.icon }}" alt="">
    175|                       </div>
    176|                     </div>
    177|                     <div class="description-col">

RuntimeError: Cannot read properties of null (reading 'icon')] {
  [stack]: 'TemplateError: anonymous:174:53\n' +
    '    172|                     <div class="buff-col">\n' +
    '    173|                       <div class="buff-icon-container">\n' +
    ' >> 174|                         <img class="buff-icon" src="{{ floor.node_2.buff.icon }}" alt="">\n' +
    '    175|                       </div>\n' +
    '    176|                     </div>\n' +
    '    177|                     <div class="description-col">\n' +
    '\n' +
    "RuntimeError: Cannot read properties of null (reading 'icon')",
  [message]: 'anonymous:174:53\n' +
    '    172|                     <div class="buff-col">\n' +
    '    173|                       <div class="buff-icon-container">\n' +
    ' >> 174|                         <img class="buff-icon" src="{{ floor.node_2.buff.icon }}" alt="">\n' +
    '    175|                       </div>\n' +
    '    176|                     </div>\n' +
    '    177|                     <div class="description-col">\n' +
    '\n' +
    "RuntimeError: Cannot read properties of null (reading 'icon')",
  name: 'TemplateError'
}

任何挑战查询均会报错，原因未知，可能与starrail插件或GT-Manual（概率不大）有关

**Comment by ZM-J** [comment]
这个是由于快速通关没有时间戳而导致的，已修复，麻烦更新。

**Comment by ZM-J** [comment]
还有一个报错成因是 #169 ，现在也已经修复了
