### ISSUE TITLE
功能更新建议：`*深渊` 并列显示三深渊的战绩，新增一个 `*最新深渊` 来查询最新的深渊信息？

### ISSUE THREAD

**Issue by ZM-J** [hewang1an/StarRail-plugin#156]
现在要查询深渊战绩的话得挨个查，如果能做到查询一次 `*深渊` 就能把三个深渊都显示出来感觉就会比较爽一点。

而且在显示三深渊的时候，还可以显示

* `NEW` 表示最新更新的深渊 
* ⏲图标（仿官方）提示即将过期的深渊

这样可能比现在查询 `*深渊` 只是在查询最新深渊要好？

当然现在的查询最新的话可以另开一个命令（

**Comment by ZM-J** [comment]
问题就是哥们的 `nodejs` 水平实在太菜了，不太知道已有的深渊模板要怎么复用才 OK

请神 @kissnavel

**Comment by kissnavel** [comment]
> 问题就是哥们的 `nodejs` 水平实在太菜了，不太知道已有的深渊模板要怎么复用才 OK
> 
> 请神 @kissnavel

别啊，我是菜鸡，代码只会复制+黏贴
查询返回结果的话，个人认为依次查询不同的深渊然后依次返回图片比较好，放一张图里会非常混乱
分别查询的功能保留，让用户自己选是一次查三个不同的深渊还是查特定的深渊
最新更新的深渊目前在左上角有NEW标识
即将过期的深渊个人没什么好的想法在生成的图片上标识
大佬快去写个判断最旧深渊即将过期的代码，然后就能加上了（

**Comment by ZM-J** [comment]
> > 问题就是哥们的 `nodejs` 水平实在太菜了，不太知道已有的深渊模板要怎么复用才 OK
> > 请神 @kissnavel
> 
> 别啊，我是菜鸡，代码只会复制+黏贴 查询返回结果的话，个人认为依次查询不同的深渊然后依次返回图片比较好，放一张图里会非常混乱 分别查询的功能保留，让用户自己选是一次查三个不同的深渊还是查特定的深渊 最新更新的深渊目前在左上角有NEW标识 即将过期的深渊个人没什么好的想法在生成的图片上标识 大佬快去写个判断最旧深渊即将过期的代码，然后就能加上了（

我一开始的预想是做成三栏显示，重新弄一个背景，或者是把背景弄淡点就行？

类似于

|UID|123456789|深渊记录|
|---|---|---|
|末日|虚构|混沌|
|末日记录|虚构记录|混沌记录|

这样

即将过期的深渊也只需要根据深渊ID去判断就行了，显示图案的话就搞个官方的那种时钟的图案。

**Comment by kissnavel** [comment]
> > > 问题就是哥们的 `nodejs` 水平实在太菜了，不太知道已有的深渊模板要怎么复用才 OK
> > > 请神 @kissnavel
> > 
> > 
> > 别啊，我是菜鸡，代码只会复制+黏贴 查询返回结果的话，个人认为依次查询不同的深渊然后依次返回图片比较好，放一张图里会非常混乱 分别查询的功能保留，让用户自己选是一次查三个不同的深渊还是查特定的深渊 最新更新的深渊目前在左上角有NEW标识 即将过期的深渊个人没什么好的想法在生成的图片上标识 大佬快去写个判断最旧深渊即将过期的代码，然后就能加上了（
> 
> 我一开始的预想是做成三栏显示，重新弄一个背景，或者是把背景弄淡点就行？
> 
> 类似于
> 
> UID	123456789	深渊记录
> 末日	虚构	混沌
> 末日记录	虚构记录	混沌记录
> 这样
> 
> 即将过期的深渊也只需要根据深渊ID去判断就行了，显示图案的话就搞个官方的那种时钟的图案。

数据可以依次查询3个深渊后存储为3个不同的数据，然后一起传入重新写的划分左、中、右显示的html调用
3种深渊显示的内容不同，忘却的比较长，显示在一张图片上另外2个深渊会有留空部分，大概拼在一起是个什么样子，可以3张深渊的查询图并排黏贴进画图里看一下，我感觉看着怪怪的就是了……
背景可以用同一个，本身显示的内容就有区别了，背景的影响倒不是很大

**Comment by ZM-J** [comment]
> > > > 问题就是哥们的 `nodejs` 水平实在太菜了，不太知道已有的深渊模板要怎么复用才 OK
> > > > 请神 @kissnavel
> > > 
> > > 
> > > 别啊，我是菜鸡，代码只会复制+黏贴 查询返回结果的话，个人认为依次查询不同的深渊然后依次返回图片比较好，放一张图里会非常混乱 分别查询的功能保留，让用户自己选是一次查三个不同的深渊还是查特定的深渊 最新更新的深渊目前在左上角有NEW标识 即将过期的深渊个人没什么好的想法在生成的图片上标识 大佬快去写个判断最旧深渊即将过期的代码，然后就能加上了（
> > 
> > 
> > 我一开始的预想是做成三栏显示，重新弄一个背景，或者是把背景弄淡点就行？
> > 类似于
> > UID	123456789	深渊记录
> > 末日	虚构	混沌
> > 末日记录	虚构记录	混沌记录
> > 这样
> > 即将过期的深渊也只需要根据深渊ID去判断就行了，显示图案的话就搞个官方的那种时钟的图案。
> 
> 数据可以依次查询3个深渊后存储为3个不同的数据，然后一起传入重新写的划分左、中、右显示的html调用 3种深渊显示的内容不同，忘却的比较长，显示在一张图片上另外2个深渊会有留空部分，大概拼在一起是个什么样子，可以3张深渊的查询图并排黏贴进画图里看一下，我感觉看着怪怪的就是了…… 背景可以用同一个，本身显示的内容就有区别了，背景的影响倒不是很大

如果忘却的比较长，可以末日/虚构/混沌都只显示最后2层的（反正11/12以前的也不会怎么关注）

**Comment by kissnavel** [comment]
> > > > > 问题就是哥们的 `nodejs` 水平实在太菜了，不太知道已有的深渊模板要怎么复用才 OK
> > > > > 请神 @kissnavel
> > > > 
> > > > 
> > > > 别啊，我是菜鸡，代码只会复制+黏贴 查询返回结果的话，个人认为依次查询不同的深渊然后依次返回图片比较好，放一张图里会非常混乱 分别查询的功能保留，让用户自己选是一次查三个不同的深渊还是查特定的深渊 最新更新的深渊目前在左上角有NEW标识 即将过期的深渊个人没什么好的想法在生成的图片上标识 大佬快去写个判断最旧深渊即将过期的代码，然后就能加上了（
> > > 
> > > 
> > > 我一开始的预想是做成三栏显示，重新弄一个背景，或者是把背景弄淡点就行？
> > > 类似于
> > > UID	123456789	深渊记录
> > > 末日	虚构	混沌
> > > 末日记录	虚构记录	混沌记录
> > > 这样
> > > 即将过期的深渊也只需要根据深渊ID去判断就行了，显示图案的话就搞个官方的那种时钟的图案。
> > 
> > 
> > 数据可以依次查询3个深渊后存储为3个不同的数据，然后一起传入重新写的划分左、中、右显示的html调用 3种深渊显示的内容不同，忘却的比较长，显示在一张图片上另外2个深渊会有留空部分，大概拼在一起是个什么样子，可以3张深渊的查询图并排黏贴进画图里看一下，我感觉看着怪怪的就是了…… 背景可以用同一个，本身显示的内容就有区别了，背景的影响倒不是很大
> 
> 如果忘却的比较长，可以末日/虚构/混沌都只显示最后2层的（反正11/12以前的也不会怎么关注）

已实现并列显示忘却、末日、虚构信息，忘却的楼层没有进行缩减（测试有人练度低打不满，缩减了反而会显示不全，其他的没打满的也会导致显示不全，3个深渊都有可能打不满，显示就会比较乱，暂时先这样吧），留空会比较大（实际做出来留空大的效果感觉还行？）
关于楼层还有一个思路是忘却保留随后3层数据，末日、虚构保留最后2层数据，详细数据可以单独查询，这样的话刚好，哪怕练度不够不打满也只会有一点点留空，除非忘却不打导致显示不全

**Comment by kissnavel** [comment]
> > > > > > 问题就是哥们的 `nodejs` 水平实在太菜了，不太知道已有的深渊模板要怎么复用才 OK
> > > > > > 请神 @kissnavel
> > > > > 
> > > > > 
> > > > > 别啊，我是菜鸡，代码只会复制+黏贴 查询返回结果的话，个人认为依次查询不同的深渊然后依次返回图片比较好，放一张图里会非常混乱 分别查询的功能保留，让用户自己选是一次查三个不同的深渊还是查特定的深渊 最新更新的深渊目前在左上角有NEW标识 即将过期的深渊个人没什么好的想法在生成的图片上标识 大佬快去写个判断最旧深渊即将过期的代码，然后就能加上了（
> > > > 
> > > > 
> > > > 我一开始的预想是做成三栏显示，重新弄一个背景，或者是把背景弄淡点就行？
> > > > 类似于
> > > > UID	123456789	深渊记录
> > > > 末日	虚构	混沌
> > > > 末日记录	虚构记录	混沌记录
> > > > 这样
> > > > 即将过期的深渊也只需要根据深渊ID去判断就行了，显示图案的话就搞个官方的那种时钟的图案。
> > > 
> > > 
> > > 数据可以依次查询3个深渊后存储为3个不同的数据，然后一起传入重新写的划分左、中、右显示的html调用 3种深渊显示的内容不同，忘却的比较长，显示在一张图片上另外2个深渊会有留空部分，大概拼在一起是个什么样子，可以3张深渊的查询图并排黏贴进画图里看一下，我感觉看着怪怪的就是了…… 背景可以用同一个，本身显示的内容就有区别了，背景的影响倒不是很大
> > 
> > 
> > 如果忘却的比较长，可以末日/虚构/混沌都只显示最后2层的（反正11/12以前的也不会怎么关注）
> 
> 已实现并列显示忘却、末日、虚构信息，忘却的楼层没有进行缩减（测试有人练度低打不满，缩减了反而会显示不全，其他的没打满的也会导致显示不全，3个深渊都有可能打不满，显示就会比较乱，暂时先这样吧），留空会比较大（实际做出来留空大的效果感觉还行？）

**Comment by ZM-J** [comment]
> > > > > > 问题就是哥们的 `nodejs` 水平实在太菜了，不太知道已有的深渊模板要怎么复用才 OK
> > > > > > 请神 @kissnavel
> > > > > 
> > > > > 
> > > > > 别啊，我是菜鸡，代码只会复制+黏贴 查询返回结果的话，个人认为依次查询不同的深渊然后依次返回图片比较好，放一张图里会非常混乱 分别查询的功能保留，让用户自己选是一次查三个不同的深渊还是查特定的深渊 最新更新的深渊目前在左上角有NEW标识 即将过期的深渊个人没什么好的想法在生成的图片上标识 大佬快去写个判断最旧深渊即将过期的代码，然后就能加上了（
> > > > 
> > > > 
> > > > 我一开始的预想是做成三栏显示，重新弄一个背景，或者是把背景弄淡点就行？
> > > > 类似于
> > > > UID	123456789	深渊记录
> > > > 末日	虚构	混沌
> > > > 末日记录	虚构记录	混沌记录
> > > > 这样
> > > > 即将过期的深渊也只需要根据深渊ID去判断就行了，显示图案的话就搞个官方的那种时钟的图案。
> > > 
> > > 
> > > 数据可以依次查询3个深渊后存储为3个不同的数据，然后一起传入重新写的划分左、中、右显示的html调用 3种深渊显示的内容不同，忘却的比较长，显示在一张图片上另外2个深渊会有留空部分，大概拼在一起是个什么样子，可以3张深渊的查询图并排黏贴进画图里看一下，我感觉看着怪怪的就是了…… 背景可以用同一个，本身显示的内容就有区别了，背景的影响倒不是很大
> > 
> > 
> > 如果忘却的比较长，可以末日/虚构/混沌都只显示最后2层的（反正11/12以前的也不会怎么关注）
> 
> 已实现并列显示忘却、末日、虚构信息，忘却的楼层没有进行缩减（测试有人练度低打不满，缩减了反而会显示不全，其他的没打满的也会导致显示不全，3个深渊都有可能打不满，显示就会比较乱，暂时先这样吧），留空会比较大（实际做出来留空大的效果感觉还行？） 关于楼层还有一个思路是忘却保留随后3层数据，末日、虚构保留最后2层数据，详细数据可以单独查询，这样的话刚好，哪怕练度不够不打满也只会有一点点留空，除非忘却不打导致显示不全

谢谢大佬的贡献，给大佬递茶

我说的就是类似于请求拿到的数组只留前3（前2）个元素，这样可能从显示清爽度来说就会比较OK（譬如一个人只能打到10层，那么就只显示8/9/10层的）

然后就是查到摆子的时候会穿（这个应该是我之前撸末日UI的时候CSS调得太拙劣了）

<img width="1272" alt="image" src="https://github.com/user-attachments/assets/2b5670f9-04cd-4161-851d-247cf66977ed">

**Comment by kissnavel** [comment]
> > > > > > > 问题就是哥们的 `nodejs` 水平实在太菜了，不太知道已有的深渊模板要怎么复用才 OK
> > > > > > > 请神 @kissnavel
> > > > > > 
> > > > > > 
> > > > > > 别啊，我是菜鸡，代码只会复制+黏贴 查询返回结果的话，个人认为依次查询不同的深渊然后依次返回图片比较好，放一张图里会非常混乱 分别查询的功能保留，让用户自己选是一次查三个不同的深渊还是查特定的深渊 最新更新的深渊目前在左上角有NEW标识 即将过期的深渊个人没什么好的想法在生成的图片上标识 大佬快去写个判断最旧深渊即将过期的代码，然后就能加上了（
> > > > > 
> > > > > 
> > > > > 我一开始的预想是做成三栏显示，重新弄一个背景，或者是把背景弄淡点就行？
> > > > > 类似于
> > > > > UID	123456789	深渊记录
> > > > > 末日	虚构	混沌
> > > > > 末日记录	虚构记录	混沌记录
> > > > > 这样
> > > > > 即将过期的深渊也只需要根据深渊ID去判断就行了，显示图案的话就搞个官方的那种时钟的图案。
> > > > 
> > > > 
> > > > 数据可以依次查询3个深渊后存储为3个不同的数据，然后一起传入重新写的划分左、中、右显示的html调用 3种深渊显示的内容不同，忘却的比较长，显示在一张图片上另外2个深渊会有留空部分，大概拼在一起是个什么样子，可以3张深渊的查询图并排黏贴进画图里看一下，我感觉看着怪怪的就是了…… 背景可以用同一个，本身显示的内容就有区别了，背景的影响倒不是很大
> > > 
> > > 
> > > 如果忘却的比较长，可以末日/虚构/混沌都只显示最后2层的（反正11/12以前的也不会怎么关注）
> > 
> > 
> > 已实现并列显示忘却、末日、虚构信息，忘却的楼层没有进行缩减（测试有人练度低打不满，缩减了反而会显示不全，其他的没打满的也会导致显示不全，3个深渊都有可能打不满，显示就会比较乱，暂时先这样吧），留空会比较大（实际做出来留空大的效果感觉还行？） 关于楼层还有一个思路是忘却保留随后3层数据，末日、虚构保留最后2层数据，详细数据可以单独查询，这样的话刚好，哪怕练度不够不打满也只会有一点点留空，除非忘却不打导致显示不全
> 
> 谢谢大佬的贡献，给大佬递茶
> 
> 我说的就是类似于请求拿到的数组只留前3（前2）个元素，这样可能从显示清爽度来说就会比较OK（譬如一个人只能打到10层，那么就只显示8/9/10层的）
> 
> 然后就是查到摆子的时候会穿（这个应该是我之前撸末日UI的时候CSS调得太拙劣了）
> 
> <img alt="image" width="1272" src="https://private-user-images.githubusercontent.com/21689514/358498755-2b5670f9-04cd-4161-851d-247cf66977ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTMzODQsIm5iZiI6MTcyMzc5MzA4NCwicGF0aCI6Ii8yMTY4OTUxNC8zNTg0OTg3NTUtMmI1NjcwZjktMDRjZC00MTYxLTg1MWQtMjQ3Y2Y2Njk3N2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA3MjQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZmZlNGM5YTAzMDQyMTM2NDk4ZGY2Y2FhODdhMjAzOTNkMDJiNjIxZDVmMzAzYWMxMDdmMmQwY2I5Y2FlYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LDa_0HMyXjEzrGkqmffZFi_Wm5z3Uc-V2XskW1pLx3k">

碰到摆子确实会穿，而且因为有3个深渊所以有各种穿法
目前是按照左侧的html来计算头尾距离，中间和右侧是靠top来拉开头部距离，穿是必然的

**Comment by ZM-J** [comment]
> > > > > > > > 问题就是哥们的 `nodejs` 水平实在太菜了，不太知道已有的深渊模板要怎么复用才 OK
> > > > > > > > 请神 @kissnavel
> > > > > > > 
> > > > > > > 
> > > > > > > 别啊，我是菜鸡，代码只会复制+黏贴 查询返回结果的话，个人认为依次查询不同的深渊然后依次返回图片比较好，放一张图里会非常混乱 分别查询的功能保留，让用户自己选是一次查三个不同的深渊还是查特定的深渊 最新更新的深渊目前在左上角有NEW标识 即将过期的深渊个人没什么好的想法在生成的图片上标识 大佬快去写个判断最旧深渊即将过期的代码，然后就能加上了（
> > > > > > 
> > > > > > 
> > > > > > 我一开始的预想是做成三栏显示，重新弄一个背景，或者是把背景弄淡点就行？
> > > > > > 类似于
> > > > > > UID	123456789	深渊记录
> > > > > > 末日	虚构	混沌
> > > > > > 末日记录	虚构记录	混沌记录
> > > > > > 这样
> > > > > > 即将过期的深渊也只需要根据深渊ID去判断就行了，显示图案的话就搞个官方的那种时钟的图案。
> > > > > 
> > > > > 
> > > > > 数据可以依次查询3个深渊后存储为3个不同的数据，然后一起传入重新写的划分左、中、右显示的html调用 3种深渊显示的内容不同，忘却的比较长，显示在一张图片上另外2个深渊会有留空部分，大概拼在一起是个什么样子，可以3张深渊的查询图并排黏贴进画图里看一下，我感觉看着怪怪的就是了…… 背景可以用同一个，本身显示的内容就有区别了，背景的影响倒不是很大
> > > > 
> > > > 
> > > > 如果忘却的比较长，可以末日/虚构/混沌都只显示最后2层的（反正11/12以前的也不会怎么关注）
> > > 
> > > 
> > > 已实现并列显示忘却、末日、虚构信息，忘却的楼层没有进行缩减（测试有人练度低打不满，缩减了反而会显示不全，其他的没打满的也会导致显示不全，3个深渊都有可能打不满，显示就会比较乱，暂时先这样吧），留空会比较大（实际做出来留空大的效果感觉还行？） 关于楼层还有一个思路是忘却保留随后3层数据，末日、虚构保留最后2层数据，详细数据可以单独查询，这样的话刚好，哪怕练度不够不打满也只会有一点点留空，除非忘却不打导致显示不全
> > 
> > 
> > 谢谢大佬的贡献，给大佬递茶
> > 我说的就是类似于请求拿到的数组只留前3（前2）个元素，这样可能从显示清爽度来说就会比较OK（譬如一个人只能打到10层，那么就只显示8/9/10层的）
> > 然后就是查到摆子的时候会穿（这个应该是我之前撸末日UI的时候CSS调得太拙劣了）
> > <img alt="image" width="1272" src="https://private-user-images.githubusercontent.com/21689514/358498755-2b5670f9-04cd-4161-851d-247cf66977ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3OTMzODQsIm5iZiI6MTcyMzc5MzA4NCwicGF0aCI6Ii8yMTY4OTUxNC8zNTg0OTg3NTUtMmI1NjcwZjktMDRjZC00MTYxLTg1MWQtMjQ3Y2Y2Njk3N2VkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE2VDA3MjQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjZmZlNGM5YTAzMDQyMTM2NDk4ZGY2Y2FhODdhMjAzOTNkMDJiNjIxZDVmMzAzYWMxMDdmMmQwY2I5Y2FlYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LDa_0HMyXjEzrGkqmffZFi_Wm5z3Uc-V2XskW1pLx3k">
> 
> 碰到摆子确实会穿，而且因为有3个深渊所以有各种穿法 目前是按照左侧的html来计算头尾距离，中间和右侧是靠top来拉开头部距离，穿是必然的

总之这个已经可用了，再次感谢大佬的付出

**Comment by kissnavel** [comment]
![024f160c0dac8a037213239a04222bd8](https://github.com/user-attachments/assets/77f70240-8be4-4e87-bf52-79d12a068ffc)
这下就全搞完了
