### ISSUE TITLE
抽卡链接绑定正则建议

### ISSUE THREAD

**Issue by GOOD-AN** [hewang1an/StarRail-plugin#17]
有人会发送#星铁抽卡链接绑定，最后带绑定两个字，所以正则这样写是不是更适配一点: ^#星铁抽卡链接(绑定)?$

**Comment by zipated** [comment]
![image](https://user-images.githubusercontent.com/25282429/235817024-b64e5e66-4b5c-44b2-bbaf-267b212da9f8.png)
笑死(

**Comment by TsukinaKasumi** [comment]
感谢建议，这两天事情较多，正则会慢慢优化

**Comment by GOOD-AN** [comment]
辛苦大佬
