### ISSUE TITLE
抽卡记录做成喵喵plugin那样只显示抽到的5星数量和已经垫了多少抽就足够了，没必要显示4星

### ISSUE THREAD

**Issue by AizawaHikaru233** [hewang1an/StarRail-plugin#20]

**Comment by AizawaHikaru233** [comment]
另外就是，可不可以添加一个直接通过stoken获取cookie的功能？逍遥cvs扫码登录是已经获取了stoken了的。

**Comment by TsukinaKasumi** [comment]
抽卡记录最初的话并没有考虑太多，因为是临时写出来的东西所以很多东西要改，之后会改成只显示五星和垫了多少抽，通过sk绑ck的我后面在看看吧
