### ISSUE TITLE
抽卡记录详情相关

### ISSUE THREAD

**Issue by zipated** [hewang1an/StarRail-plugin#23]
现在物品名后面的数字是和上个同星级之间相隔的（垫的）数目，希望可以改成相对第几抽抽到的数目

**Comment by Lycofuture** [comment]
> 

云崽本体已实现此功能

**Comment by Lycofuture** [comment]
> 现在物品名后面的数字是和上个同星级之间相隔的（垫的）数目，希望可以改成相对第几抽抽到的数目

云崽本体已实现此功能
