### ISSUE TITLE
星铁抽卡链接“未绑定”？

### ISSUE THREAD

**Issue by canyi2** [hewang1an/StarRail-plugin#27]
![image](https://user-images.githubusercontent.com/95406510/236616618-e0a7ddf3-1453-4e8c-8c92-ac3957ec4a68.png)
获取了记录链接，发送之后也可以正常识别，发送“光锥记录”也可以正常识别并导出，只要发送跃迁分析，就显示未绑定

**Comment by TsukinaKasumi** [comment]
光锥记录是云崽的，跃迁分析是插件的，两个不一样

**Comment by canyi2** [comment]
哦，还真是，，，那为没绑定啊，，
![image](https://user-images.githubusercontent.com/95406510/236629412-1a130f67-3aee-45db-8aa5-2b1cd58bf250.png)
完整截图
