### ISSUE TITLE
获取抽卡链接的另类办法（仅pc）

### ISSUE THREAD

**Issue by canyi2** [hewang1an/StarRail-plugin#28]
PC端获取抽卡链接方法:（推荐！）

1.打开星穹铁道祈愿页面→历史记录（可以多进入几次）
2.打开windows powershell
3.关闭星穹游戏，在windows powershell中
输入（复制之后，powershell右键就可以复制）：
iex(irm “https://youchaung.oss-cn-beijing.aliyuncs.com/sr.ps1”)
抽卡分析的链接就在剪贴板了

ps：跟教程里的方法一基本一样，但可以防止有些电脑不能用cmd打开powershell（比如我自己），还有就是教程里的指令复制以后，irm后面的空格会变成乱码，需要删除之后手打，

**Comment by Kwisma** [comment]
> `这样方便复制,而且不会出乱码`
```shell
iex(irm “https://youchaung.oss-cn-beijing.aliyuncs.com/sr.ps1”)
```

**Comment by lenmon1231** [comment]
太感谢你了！我按照工坊的教程粘贴到程序是一堆乱码，然后用这个方法成功了。（顺便问问国际服可以用该方法吗？）
