### ISSUE TITLE
增加查看群友信息的功能

### ISSUE THREAD

**Issue by xmexg** [hewang1an/StarRail-plugin#31]
希望增加查看群友的功能，比如:  
#星铁卡片 @(某群友)  
#星铁卡片 1001234123  
![Screenshot_2023-05-08-10-05-30-646_com.tencent.mobileqq-edit.jpg](https://user-images.githubusercontent.com/42137636/236718681-f8def052-f57e-4c88-9521-95ac1aee0127.jpg)

**Comment by TsukinaKasumi** [comment]
直接at对方然后＋指令应该是可以看的，不过看不了全部，而且uid和等级显示的是你自己的，因为uid和等级是通过ck拿的

**Comment by xmexg** [comment]
希望当@对方后以被@的用户的ck获取数据,  如果对方未绑定ck的话给出提示"对方未绑定ck",  这样实现查看群友信息的功能
