### ISSUE TITLE
建议提示

### ISSUE THREAD

**Issue by yelinlan** [hewang1an/StarRail-plugin#34]
![image](https://user-images.githubusercontent.com/38036830/236860942-8afe0b9c-03b7-4729-9684-1cf4fd9d19ca.png)
在回复 请先登录时，告诉我怎么登录，至少可以提示  #星铁帮助 命令可以查看帮助。这样使用的人知道怎么登陆，在哪里可以得到帮助。

**Comment by TsukinaKasumi** [comment]
“请先登陆”是你发啥指令触发的？插件里貌似没有这样一个提示

**Comment by yelinlan** [comment]
> “请先登陆”是你发啥指令触发的？插件里貌似没有这样一个提示

![image](https://user-images.githubusercontent.com/38036830/237036500-2c5396d4-0df4-4141-b6c0-6d2a584c9d7f.png)

**Comment by TsukinaKasumi** [comment]
好的，这两天发烧了，等病好了再改吧
