### ISSUE TITLE
#星铁体力 报错

### ISSUE THREAD

**Issue by cocoyamnut** [hewang1an/StarRail-plugin#36]
![image](https://user-images.githubusercontent.com/99504275/236995597-dc4c1091-a01d-4d5f-abe6-4513a72ed08a.png)
![image](https://user-images.githubusercontent.com/99504275/236995637-2b7f1249-c11e-4d54-bbae-f522fd78b7be.png)

**Comment by TsukinaKasumi** [comment]
uid和ck都绑了吗，感觉是数据没拿到吧，我后面加个报错提示吧

**Comment by cocoyamnut** [comment]
绑定的，但接口返回为空，但返回了，状态码
