### ISSUE TITLE
抽卡记录链接似乎能靠cookie拼出来，能否考虑支持一下直接通过米游社cookie来获取祈愿记录？

### ISSUE THREAD

**Issue by genshinclangpornfessor** [hewang1an/StarRail-plugin#38]
最近闲着没事分析了下隔壁Snap Hutao的代码，感觉这个链接是可以靠stoken拿到的

一些关键点：

https://github.com/DGP-Studio/Snap.Hutao/blob/33935dabc23a00e25069650ab3f05f425e0fed5f/src/Snap.Hutao/Snap.Hutao/Web/ApiEndpoints.cs#LL232C28-L232C29

https://github.com/DGP-Studio/Snap.Hutao/blob/33935dabc23a00e25069650ab3f05f425e0fed5f/src/Snap.Hutao/Snap.Hutao/Web/Hoyolab/Hk4e/Event/GachaInfo/GachaInfoClient.cs#L28

https://github.com/DGP-Studio/Snap.Hutao/blob/33935dabc23a00e25069650ab3f05f425e0fed5f/src/Snap.Hutao/Snap.Hutao/Web/Hoyolab/DynamicSecret/DynamicSecretHandler.cs#L14

https://github.com/DGP-Studio/Snap.Hutao/blob/33935dabc23a00e25069650ab3f05f425e0fed5f/src/Snap.Hutao/Snap.Hutao/Web/Hoyolab/DynamicSecret/DynamicSecretCreationOptions.cs#L6

https://github.com/DGP-Studio/Snap.Hutao/blob/33935dabc23a00e25069650ab3f05f425e0fed5f/src/Snap.Hutao/Snap.Hutao/Web/Hoyolab/Hk4e/Event/GachaInfo/GachaLogQueryOptions.cs#L72

要不要考虑支持下🥰

当然这个前提是，原神的算authKey的算法跟崩铁是一样的，如果不一样就当我没说吧。

**Comment by TsukinaKasumi** [comment]
崩铁和原神的authkey算法不一样，第一天就试过了
