### ISSUE TITLE
建议更改未绑定ck用户使用指令时的提示语

### ISSUE THREAD

**Issue by HugeByte** [hewang1an/StarRail-plugin#39]
目前提示语是【请安装逍遥插件并扫码绑定才能使用本功能哦】，但一般用户无法理解逍遥插件是什么
建议改成【未绑定帐号，请发送 #扫码登录，并使用米游社app扫码绑定后重试】之类的提示语，用户会更清楚接下来应该干什么

**Comment by TsukinaKasumi** [comment]
感谢建议
