### ISSUE TITLE
一个奇怪的bug

### ISSUE THREAD

**Issue by slideslide** [hewang1an/StarRail-plugin#40]
![image](https://github.com/hewang1an/StarRail-plugin/assets/86949124/2ff966bf-7fc5-4571-9694-f3a578d75ab2)

uid：100075060
已绑定ck但是properties却是null

**Comment by TsukinaKasumi** [comment]
可能是有什么问题，这两天阳了，等过两天病好了抽空优化一下吧

**Comment by slideslide** [comment]
> 可能是有什么问题，这两天阳了，等过两天病好了抽空优化一下吧

感谢，保重身体。
