### ISSUE TITLE
体力面板读不出来

### ISSUE THREAD

**Issue by Euyug** [hewang1an/StarRail-plugin#47]
其他功能都行，包括抽卡，角色面板。就是体力面板读不出来
![image](https://github.com/hewang1an/StarRail-plugin/assets/55316427/9eb55b44-4dcb-49c7-95de-0dad8f8623e1)
![image](https://github.com/hewang1an/StarRail-plugin/assets/55316427/be006356-0b5a-4453-882d-65b19413077c)

扫码绑定和手动绑定都试过，stoken和ck看起来也是正常的

**Comment by Euyug** [comment]
![image](https://github.com/hewang1an/StarRail-plugin/assets/55316427/dce86301-5710-409c-a4c8-c2113f38afab)
尝试读取返回信息，但是不知道返回了什么钩8

**Comment by TsukinaKasumi** [comment]
昨天开始查体力开始铺开验证码了，可能是遇到验证码了

**Comment by Euyug** [comment]
> 
hh群里就他一个人查不出来，我们一致认为他号的问题
