### ISSUE TITLE
星铁相关插件正则修改建议

### ISSUE THREAD

**Issue by Capybara-sea** [hewang1an/StarRail-plugin#48]
是否可以考虑像隔壁那样增加 `*` + 命令的形式来统一增加新的正则。
在不删除原有的情况下把皆如：
- #希儿攻略 -> *希儿攻略
- #星铁绑定uid -> *绑定uid
- #星铁收入 -> *收入
- #星铁体力 -> *体力
- #星铁探索 -> *探索

这样的方式来减少输入星铁的次数

**Comment by TsukinaKasumi** [comment]
之前问过群里大众的意见了，大家似乎习惯用#了，晚点再问问大众的意见吧

**Comment by ArisCM** [comment]
> 之前问过群里大众的意见了，大家似乎习惯用#了，晚点再问问大众的意见吧

或者是配置文件里让大伙自定义触发前缀呢？

**Comment by Capybara-sea** [comment]
> 之前问过群里大众的意见了，大家似乎习惯用#了，晚点再问问大众的意见吧

所以我的建议是在不改变现有规则下增加，因为先在已经搞得有些要加星铁有些又不要加了，全混乱了，增加一个通过星号来独立出来我认为是好的。

**Comment by KeyPJ** [comment]
*号与[Atlas](https://gitee.com/Nwflower/atlas)冲突了
