### ISSUE TITLE
#星铁在线时长报错

### ISSUE THREAD

**Issue by liuzj288** [hewang1an/StarRail-plugin#49]
![image](https://github.com/hewang1an/StarRail-plugin/assets/13833404/452a5ac7-7e27-4651-96d0-e79b282396c8)

**Comment by WaterEmissary** [comment]
我也遇到了，打印了下日志发现查询的功能是正常的，但是会进入一个死循环，然后返回一个报错的html
![1](https://github.com/hewang1an/StarRail-plugin/assets/41639205/d9e38ef3-d054-46bb-85f8-f0dc20b7731b)
![2](https://github.com/hewang1an/StarRail-plugin/assets/41639205/da783909-6e07-4ac0-a9fc-47bd0ab93b5f)
估计是接口那有问题

**Comment by ikechan8370** [comment]
应该是记录太多了（看来你在线时长很长） 然后一直查被阻断了。后续做个时间限制 只查最近七天

**Comment by ikechan8370** [comment]
改了一下，更新试试？
