### ISSUE TITLE
#星铁更新面板 功能未验证用户是否已登录

### ISSUE THREAD

**Issue by xmexg** [hewang1an/StarRail-plugin#53]
当未绑定ck的用户使用#星铁更新面板功能时，不会提示未绑定ck，而是真的去更新面板且无后续

**Comment by TsukinaKasumi** [comment]
更新面板不需要ck，更新之后无后续建议看看日志是否有报错，如果提示未查询到数据先把服务器时间校准一下，给如果时间差太大的话会默认是伪造的

**Comment by xmexg** [comment]
已解决
