### ISSUE TITLE
模拟抽卡出金抽取数量角标遮挡

### ISSUE THREAD

**Issue by GOOD-AN** [hewang1an/StarRail-plugin#54]
如果出金刚好在右上角，角标会被遮挡
![QHY$T4$LTFNPBVFU}S14@}V](https://github.com/hewang1an/StarRail-plugin/assets/53306377/37f3e20e-d48e-4e52-830e-b710112281a3)
是不是可以改到右下角？

**Comment by bietiaop** [comment]
抽空看看
