### ISSUE TITLE
关于国际服的问题

### ISSUE THREAD

**Issue by kissnavel** [hewang1an/StarRail-plugin#55]
ck仅1个是新获取的，同时有原神和星铁，yunzai本体能签到，星铁uid也单独绑定了。

**Comment by Kochisa** [comment]
5.21更新：支持查询全平台数据(包括欧服以及美服），在config/panelAPI内将API修改为sr.ikechan8370 

选择的API正确我也还是和你一样，难道说亚服现在不行么。

**Comment by hyouyaka** [comment]
我是美服也是同样提示ck无铁道的角色，是因为hoyolab现在还没有相关功能吗

**Comment by TsukinaKasumi** [comment]
应该是的。

**Comment by kissnavel** [comment]
国际服目前开放战绩和养成计算器了，仍然报无可用角色。

**Comment by MamboJiang** [comment]
如果直接私聊发hoyolab的cookie， 会说“绑定cookie失败：该账号尚未绑定原神或星穹角色！”。还没有办法解决吗？

**Comment by kissnavel** [comment]
已提pr添加国际服支持，国际服大部分功能可用，仅路径不同没做区分的不可用，可以等合并或者自己按照pr改，又或者拉我的仓库，等合并后再切回这里。
