### ISSUE TITLE
*更新面板提示面板服务连接超时，请稍后重试

### ISSUE THREAD

**Issue by k1ngr4m** [hewang1an/StarRail-plugin#58]
输入指令：*更新面板 会提示Error: 面板服务连接超时，请稍后重试。
后台日志：
![image](https://github.com/hewang1an/StarRail-plugin/assets/88479528/3c0302ee-e3b7-4abb-877b-3e37ced33f34)
是网络问题？

**Comment by TsukinaKasumi** [comment]
将config/panelAPI.js里的api改成sr.ikechan8370.com就好了，如果这个连不上那就是有时候服务器抽风了，等段时间就可以了。

**Comment by k1ngr4m** [comment]
> 将config/panelAPI.js里的api改成sr.ikechan8370.com就好了，如果这个连不上那就是有时候服务器抽风了，等段时间就可以了。

感谢，有用，连上了

**Comment by lin-junliang** [comment]
又不管用了
