### ISSUE TITLE
Cannot find authkey.js

### ISSUE THREAD

**Issue by ziiqq** [hewang1an/StarRail-plugin#6]
Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'C:\Users\Administrator\Desktop\Yunzai-Bot-3.0\plugins\StarRail-plugin\utils\authkey.js' imported from C:\Users\Administrator\Desktop\Yunzai-Bot-3.0\plugins\StarRail-plugin\apps\hkrpg.js

缺少authkey.js耶

**Comment by TsukinaKasumi** [comment]
路径忘记改了，一会修复
