### ISSUE TITLE
部分命令没有未绑定cookie提示

### ISSUE THREAD

**Issue by ddls14fx** [hewang1an/StarRail-plugin#60]
例如体力只会报错，没有任何消息发送，卡片会正常提示绑定ck。建议对每个需要cookie的命令先check。

**Comment by TsukinaKasumi** [comment]
体力没绑ck的话会返回提示吧

**Comment by ddls14fx** [comment]
TypeError: mysUser.getUid is not a function
位置在StarRail-plugin/utils/common.js:222:20
在genshin\model\mys\NoteUser.js的224行getMysUser方法判断没有ck和ck下没有uid则返回false。
