### ISSUE TITLE
体力 一直提示遇到验证码

### ISSUE THREAD

**Issue by XJLZ** [hewang1an/StarRail-plugin#70]
*体力 一直提示遇到验证码，手机进米友社查看，并未发现验证码，已经扫码绑定了CK 
![image](https://github.com/hewang1an/StarRail-plugin/assets/28652248/d630f18b-7668-47fc-b04f-ffe8f0f8b32f)
![image](https://github.com/hewang1an/StarRail-plugin/assets/28652248/e3e16317-cb02-4889-a710-5775bbf96652)

**Comment by TsukinaKasumi** [comment]
的确是验证码，铁道的验证码目前没法解，上米游社不会弹很正常
