### ISSUE TITLE
指令冲突问题

### ISSUE THREAD

**Issue by Loyreau** [hewang1an/StarRail-plugin#71]
因为现在喵喵家的云崽还有插件也开始支持星铁信息查询了

有好些指令就开始冲突了

比如绑定 UID，像在 SRP 绑定里绑定uid和 喵喵 绑定uid的命令冲突， SRP 的优先级更高，所以只能给 SRP 绑定uid

有点难取舍了 因为这俩插件都做得很好，喵喵的UI很统一很美观大方，SRP这边功能齐全

所以很苦恼

**Comment by touchscale** [comment]
https://gitee.com/yoimiya-kokomi/miao-plugin/issues/I7EDHN

**Comment by touchscale** [comment]
可以参考这个
