### ISSUE TITLE
 [星铁别名]未找到角色

### ISSUE THREAD

**Issue by a4035535** [hewang1an/StarRail-plugin#74]
[11:21:45.250][ERRO] [星铁别名]未找到角色

[11:21:45.249][MARK] [米游社星铁攻略][strategy][私聊][xxx] #希儿攻略

不知道为什么都会提示未找到角色，这边直接更新的插件，没做任何修改，重装后问题依旧
其他角色也是一个问题

**Comment by touchscale** [comment]
最新版本指令前缀是以*或#星铁开头，建议仔细看帮助

**Comment by a4035535** [comment]
get 感谢 后面查了下OK了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月7日(星期五) 中午12:40
收件人: ***@***.***&gt;; 
抄送: "Amon ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hewang1an/StarRail-plugin]  [星铁别名]未找到角色 (Issue #74)





 
最新版本指令前缀是以*或#星铁开头，建议仔细看帮助
